export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SELECT_ARTICLES = 'SELECT_ARTICLES'

export const FILTER_ARTICLES = 'FILTER_ARTICLES'

export const DATE_RANGE = 'DATE_RANGE'

export const SELECT_ARTICLES_BY_DATE = 'SELECT_ARTICLES_BY_DATE'
